name: lumina_chat
description: The most sophisticated personality-matching real-time chat application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  
  # Authentication
  google_sign_in: 6.3.0
  local_auth: ^2.1.7
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.3
  
  # UI & Animations
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.1.0
  
  # Images & Media
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  image_cropper: ^8.1.0
  photo_view: ^0.14.0
  file_picker: ^8.0.3
  
  # Audio
  audioplayers: ^5.2.1
  audio_waveforms: ^1.0.5
  record: ^6.0.0
  
  # Location & Permissions
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0
  
  # Utilities
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  intl: ^0.19.0
  emoji_picker_flutter: ^1.6.3
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  path: ^1.8.3
  path_provider: ^2.1.2
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # HTTP & Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  
  # Encryption
  encrypt: ^5.0.1
  crypto: ^3.0.6
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # Date & Time
  timeago: ^3.6.0
  
  # Forms & Validation
  reactive_forms: ^16.1.1
  
  # Sensors
  sensors_plus: ^4.0.2
  firebase_remote_config: ^4.4.7
  cloudinary_flutter: ^1.3.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  
  # Testing
  mocktail: ^1.0.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/sounds/
