// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-your-web-api-key-here',
    appId: '1:123456789:web:your-app-id-here',
    messagingSenderId: '123456789',
    projectId: 'lumina-chat-project',
    authDomain: 'lumina-chat-project.firebaseapp.com',
    storageBucket: 'lumina-chat-project.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-your-android-api-key-here',
    appId: '1:123456789:android:your-app-id-here',
    messagingSenderId: '123456789',
    projectId: 'lumina-chat-project',
    storageBucket: 'lumina-chat-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX-your-ios-api-key-here',
    appId: '1:123456789:ios:your-app-id-here',
    messagingSenderId: '123456789',
    projectId: 'lumina-chat-project',
    storageBucket: 'lumina-chat-project.appspot.com',
    iosClientId: 'your-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.luminachat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX-your-macos-api-key-here',
    appId: '1:123456789:ios:your-app-id-here',
    messagingSenderId: '123456789',
    projectId: 'lumina-chat-project',
    storageBucket: 'lumina-chat-project.appspot.com',
    iosClientId: 'your-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.luminachat.app',
  );
}
